/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "rpc_layer.pb-c.h"
void   rpc_layer__read_dir_request__init
                     (RpcLayer__ReadDirRequest         *message)
{
  static RpcLayer__ReadDirRequest init_value = RPC_LAYER__READ_DIR_REQUEST__INIT;
  *message = init_value;
}
size_t rpc_layer__read_dir_request__get_packed_size
                     (const RpcLayer__ReadDirRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__read_dir_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_layer__read_dir_request__pack
                     (const RpcLayer__ReadDirRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__read_dir_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_layer__read_dir_request__pack_to_buffer
                     (const RpcLayer__ReadDirRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__read_dir_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcLayer__ReadDirRequest *
       rpc_layer__read_dir_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcLayer__ReadDirRequest *)
     protobuf_c_message_unpack (&rpc_layer__read_dir_request__descriptor,
                                allocator, len, data);
}
void   rpc_layer__read_dir_request__free_unpacked
                     (RpcLayer__ReadDirRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__read_dir_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc_layer__read_dir_response__init
                     (RpcLayer__ReadDirResponse         *message)
{
  static RpcLayer__ReadDirResponse init_value = RPC_LAYER__READ_DIR_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc_layer__read_dir_response__get_packed_size
                     (const RpcLayer__ReadDirResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__read_dir_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_layer__read_dir_response__pack
                     (const RpcLayer__ReadDirResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__read_dir_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_layer__read_dir_response__pack_to_buffer
                     (const RpcLayer__ReadDirResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__read_dir_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcLayer__ReadDirResponse *
       rpc_layer__read_dir_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcLayer__ReadDirResponse *)
     protobuf_c_message_unpack (&rpc_layer__read_dir_response__descriptor,
                                allocator, len, data);
}
void   rpc_layer__read_dir_response__free_unpacked
                     (RpcLayer__ReadDirResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__read_dir_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc_layer__get_attr_request__init
                     (RpcLayer__GetAttrRequest         *message)
{
  static RpcLayer__GetAttrRequest init_value = RPC_LAYER__GET_ATTR_REQUEST__INIT;
  *message = init_value;
}
size_t rpc_layer__get_attr_request__get_packed_size
                     (const RpcLayer__GetAttrRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__get_attr_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_layer__get_attr_request__pack
                     (const RpcLayer__GetAttrRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__get_attr_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_layer__get_attr_request__pack_to_buffer
                     (const RpcLayer__GetAttrRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__get_attr_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcLayer__GetAttrRequest *
       rpc_layer__get_attr_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcLayer__GetAttrRequest *)
     protobuf_c_message_unpack (&rpc_layer__get_attr_request__descriptor,
                                allocator, len, data);
}
void   rpc_layer__get_attr_request__free_unpacked
                     (RpcLayer__GetAttrRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__get_attr_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc_layer__get_attr_response__init
                     (RpcLayer__GetAttrResponse         *message)
{
  static RpcLayer__GetAttrResponse init_value = RPC_LAYER__GET_ATTR_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc_layer__get_attr_response__get_packed_size
                     (const RpcLayer__GetAttrResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__get_attr_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_layer__get_attr_response__pack
                     (const RpcLayer__GetAttrResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__get_attr_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_layer__get_attr_response__pack_to_buffer
                     (const RpcLayer__GetAttrResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__get_attr_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcLayer__GetAttrResponse *
       rpc_layer__get_attr_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcLayer__GetAttrResponse *)
     protobuf_c_message_unpack (&rpc_layer__get_attr_response__descriptor,
                                allocator, len, data);
}
void   rpc_layer__get_attr_response__free_unpacked
                     (RpcLayer__GetAttrResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rpc_layer__get_attr_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpc_layer__read_dir_request__field_descriptors[1] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpcLayer__ReadDirRequest, path),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_layer__read_dir_request__field_indices_by_name[] = {
  0,   /* field[0] = path */
};
static const ProtobufCIntRange rpc_layer__read_dir_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc_layer__read_dir_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpcLayer.ReadDirRequest",
  "ReadDirRequest",
  "RpcLayer__ReadDirRequest",
  "RpcLayer",
  sizeof(RpcLayer__ReadDirRequest),
  1,
  rpc_layer__read_dir_request__field_descriptors,
  rpc_layer__read_dir_request__field_indices_by_name,
  1,  rpc_layer__read_dir_request__number_ranges,
  (ProtobufCMessageInit) rpc_layer__read_dir_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc_layer__read_dir_response__field_descriptors[1] =
{
  {
    "elements",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(RpcLayer__ReadDirResponse, n_elements),
    PROTOBUF_C_OFFSETOF(RpcLayer__ReadDirResponse, elements),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_layer__read_dir_response__field_indices_by_name[] = {
  0,   /* field[0] = elements */
};
static const ProtobufCIntRange rpc_layer__read_dir_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc_layer__read_dir_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpcLayer.ReadDirResponse",
  "ReadDirResponse",
  "RpcLayer__ReadDirResponse",
  "RpcLayer",
  sizeof(RpcLayer__ReadDirResponse),
  1,
  rpc_layer__read_dir_response__field_descriptors,
  rpc_layer__read_dir_response__field_indices_by_name,
  1,  rpc_layer__read_dir_response__number_ranges,
  (ProtobufCMessageInit) rpc_layer__read_dir_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc_layer__get_attr_request__field_descriptors[1] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpcLayer__GetAttrRequest, path),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_layer__get_attr_request__field_indices_by_name[] = {
  0,   /* field[0] = path */
};
static const ProtobufCIntRange rpc_layer__get_attr_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc_layer__get_attr_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpcLayer.GetAttrRequest",
  "GetAttrRequest",
  "RpcLayer__GetAttrRequest",
  "RpcLayer",
  sizeof(RpcLayer__GetAttrRequest),
  1,
  rpc_layer__get_attr_request__field_descriptors,
  rpc_layer__get_attr_request__field_indices_by_name,
  1,  rpc_layer__get_attr_request__number_ranges,
  (ProtobufCMessageInit) rpc_layer__get_attr_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc_layer__get_attr_response__field_descriptors[4] =
{
  {
    "fileExist",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpcLayer__GetAttrResponse, fileexist),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpcLayer__GetAttrResponse, mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nlinks",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpcLayer__GetAttrResponse, nlinks),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RpcLayer__GetAttrResponse, size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_layer__get_attr_response__field_indices_by_name[] = {
  0,   /* field[0] = fileExist */
  1,   /* field[1] = mode */
  2,   /* field[2] = nlinks */
  3,   /* field[3] = size */
};
static const ProtobufCIntRange rpc_layer__get_attr_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor rpc_layer__get_attr_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RpcLayer.GetAttrResponse",
  "GetAttrResponse",
  "RpcLayer__GetAttrResponse",
  "RpcLayer",
  sizeof(RpcLayer__GetAttrResponse),
  4,
  rpc_layer__get_attr_response__field_descriptors,
  rpc_layer__get_attr_response__field_indices_by_name,
  1,  rpc_layer__get_attr_response__number_ranges,
  (ProtobufCMessageInit) rpc_layer__get_attr_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor rpc_layer__remote_ext2__method_descriptors[2] =
{
  { "ReadDir", &rpc_layer__read_dir_request__descriptor, &rpc_layer__read_dir_response__descriptor },
  { "GetAttr", &rpc_layer__get_attr_request__descriptor, &rpc_layer__get_attr_response__descriptor },
};
const unsigned rpc_layer__remote_ext2__method_indices_by_name[] = {
  1,        /* GetAttr */
  0         /* ReadDir */
};
const ProtobufCServiceDescriptor rpc_layer__remote_ext2__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "RpcLayer.RemoteExt2",
  "ReadDir",
  "RpcLayer__RemoteExt2",
  "RpcLayer",
  2,
  rpc_layer__remote_ext2__method_descriptors,
  rpc_layer__remote_ext2__method_indices_by_name
};
void rpc_layer__remote_ext2__read_dir(ProtobufCService *service,
                                      const RpcLayer__ReadDirRequest *input,
                                      RpcLayer__ReadDirResponse_Closure closure,
                                      void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &rpc_layer__remote_ext2__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc_layer__remote_ext2__get_attr(ProtobufCService *service,
                                      const RpcLayer__GetAttrRequest *input,
                                      RpcLayer__GetAttrResponse_Closure closure,
                                      void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &rpc_layer__remote_ext2__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc_layer__remote_ext2__init (RpcLayer__RemoteExt2_Service *service,
                                   RpcLayer__RemoteExt2_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &rpc_layer__remote_ext2__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
