/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_rpc_5flayer_2eproto__INCLUDED
#define PROTOBUF_C_rpc_5flayer_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _RpcLayer__ReadDirRequest RpcLayer__ReadDirRequest;
typedef struct _RpcLayer__ReadDirResponse RpcLayer__ReadDirResponse;
typedef struct _RpcLayer__GetAttrRequest RpcLayer__GetAttrRequest;
typedef struct _RpcLayer__GetAttrResponse RpcLayer__GetAttrResponse;
typedef struct _RpcLayer__ReadRequest RpcLayer__ReadRequest;
typedef struct _RpcLayer__ReadResponse RpcLayer__ReadResponse;
typedef struct _RpcLayer__WriteRequest RpcLayer__WriteRequest;
typedef struct _RpcLayer__WriteResponse RpcLayer__WriteResponse;


/* --- enums --- */


/* --- messages --- */

struct  _RpcLayer__ReadDirRequest
{
  ProtobufCMessage base;
  char *path;
};
#define RPC_LAYER__READ_DIR_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpc_layer__read_dir_request__descriptor) \
    , NULL }


struct  _RpcLayer__ReadDirResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean error;
  uint32_t error_code;
  size_t n_elements;
  char **elements;
};
#define RPC_LAYER__READ_DIR_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpc_layer__read_dir_response__descriptor) \
    , 0, 0, 0,NULL }


struct  _RpcLayer__GetAttrRequest
{
  ProtobufCMessage base;
  char *path;
};
#define RPC_LAYER__GET_ATTR_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpc_layer__get_attr_request__descriptor) \
    , NULL }


struct  _RpcLayer__GetAttrResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean error;
  uint32_t error_code;
  protobuf_c_boolean fileexist;
  uint32_t mode;
  uint32_t nlinks;
  uint32_t blocks;
  uint32_t size;
};
#define RPC_LAYER__GET_ATTR_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpc_layer__get_attr_response__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0 }


struct  _RpcLayer__ReadRequest
{
  ProtobufCMessage base;
  char *path;
  uint32_t offset;
  uint32_t length;
};
#define RPC_LAYER__READ_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpc_layer__read_request__descriptor) \
    , NULL, 0, 0 }


struct  _RpcLayer__ReadResponse
{
  ProtobufCMessage base;
  ProtobufCBinaryData data;
  protobuf_c_boolean error;
  uint32_t error_code;
};
#define RPC_LAYER__READ_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpc_layer__read_response__descriptor) \
    , {0,NULL}, 0, 0 }


struct  _RpcLayer__WriteRequest
{
  ProtobufCMessage base;
  char *path;
  uint32_t offset;
  ProtobufCBinaryData data;
};
#define RPC_LAYER__WRITE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpc_layer__write_request__descriptor) \
    , NULL, 0, {0,NULL} }


struct  _RpcLayer__WriteResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean error;
  uint32_t error_code;
};
#define RPC_LAYER__WRITE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rpc_layer__write_response__descriptor) \
    , 0, 0 }


/* RpcLayer__ReadDirRequest methods */
void   rpc_layer__read_dir_request__init
                     (RpcLayer__ReadDirRequest         *message);
size_t rpc_layer__read_dir_request__get_packed_size
                     (const RpcLayer__ReadDirRequest   *message);
size_t rpc_layer__read_dir_request__pack
                     (const RpcLayer__ReadDirRequest   *message,
                      uint8_t             *out);
size_t rpc_layer__read_dir_request__pack_to_buffer
                     (const RpcLayer__ReadDirRequest   *message,
                      ProtobufCBuffer     *buffer);
RpcLayer__ReadDirRequest *
       rpc_layer__read_dir_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpc_layer__read_dir_request__free_unpacked
                     (RpcLayer__ReadDirRequest *message,
                      ProtobufCAllocator *allocator);
/* RpcLayer__ReadDirResponse methods */
void   rpc_layer__read_dir_response__init
                     (RpcLayer__ReadDirResponse         *message);
size_t rpc_layer__read_dir_response__get_packed_size
                     (const RpcLayer__ReadDirResponse   *message);
size_t rpc_layer__read_dir_response__pack
                     (const RpcLayer__ReadDirResponse   *message,
                      uint8_t             *out);
size_t rpc_layer__read_dir_response__pack_to_buffer
                     (const RpcLayer__ReadDirResponse   *message,
                      ProtobufCBuffer     *buffer);
RpcLayer__ReadDirResponse *
       rpc_layer__read_dir_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpc_layer__read_dir_response__free_unpacked
                     (RpcLayer__ReadDirResponse *message,
                      ProtobufCAllocator *allocator);
/* RpcLayer__GetAttrRequest methods */
void   rpc_layer__get_attr_request__init
                     (RpcLayer__GetAttrRequest         *message);
size_t rpc_layer__get_attr_request__get_packed_size
                     (const RpcLayer__GetAttrRequest   *message);
size_t rpc_layer__get_attr_request__pack
                     (const RpcLayer__GetAttrRequest   *message,
                      uint8_t             *out);
size_t rpc_layer__get_attr_request__pack_to_buffer
                     (const RpcLayer__GetAttrRequest   *message,
                      ProtobufCBuffer     *buffer);
RpcLayer__GetAttrRequest *
       rpc_layer__get_attr_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpc_layer__get_attr_request__free_unpacked
                     (RpcLayer__GetAttrRequest *message,
                      ProtobufCAllocator *allocator);
/* RpcLayer__GetAttrResponse methods */
void   rpc_layer__get_attr_response__init
                     (RpcLayer__GetAttrResponse         *message);
size_t rpc_layer__get_attr_response__get_packed_size
                     (const RpcLayer__GetAttrResponse   *message);
size_t rpc_layer__get_attr_response__pack
                     (const RpcLayer__GetAttrResponse   *message,
                      uint8_t             *out);
size_t rpc_layer__get_attr_response__pack_to_buffer
                     (const RpcLayer__GetAttrResponse   *message,
                      ProtobufCBuffer     *buffer);
RpcLayer__GetAttrResponse *
       rpc_layer__get_attr_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpc_layer__get_attr_response__free_unpacked
                     (RpcLayer__GetAttrResponse *message,
                      ProtobufCAllocator *allocator);
/* RpcLayer__ReadRequest methods */
void   rpc_layer__read_request__init
                     (RpcLayer__ReadRequest         *message);
size_t rpc_layer__read_request__get_packed_size
                     (const RpcLayer__ReadRequest   *message);
size_t rpc_layer__read_request__pack
                     (const RpcLayer__ReadRequest   *message,
                      uint8_t             *out);
size_t rpc_layer__read_request__pack_to_buffer
                     (const RpcLayer__ReadRequest   *message,
                      ProtobufCBuffer     *buffer);
RpcLayer__ReadRequest *
       rpc_layer__read_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpc_layer__read_request__free_unpacked
                     (RpcLayer__ReadRequest *message,
                      ProtobufCAllocator *allocator);
/* RpcLayer__ReadResponse methods */
void   rpc_layer__read_response__init
                     (RpcLayer__ReadResponse         *message);
size_t rpc_layer__read_response__get_packed_size
                     (const RpcLayer__ReadResponse   *message);
size_t rpc_layer__read_response__pack
                     (const RpcLayer__ReadResponse   *message,
                      uint8_t             *out);
size_t rpc_layer__read_response__pack_to_buffer
                     (const RpcLayer__ReadResponse   *message,
                      ProtobufCBuffer     *buffer);
RpcLayer__ReadResponse *
       rpc_layer__read_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpc_layer__read_response__free_unpacked
                     (RpcLayer__ReadResponse *message,
                      ProtobufCAllocator *allocator);
/* RpcLayer__WriteRequest methods */
void   rpc_layer__write_request__init
                     (RpcLayer__WriteRequest         *message);
size_t rpc_layer__write_request__get_packed_size
                     (const RpcLayer__WriteRequest   *message);
size_t rpc_layer__write_request__pack
                     (const RpcLayer__WriteRequest   *message,
                      uint8_t             *out);
size_t rpc_layer__write_request__pack_to_buffer
                     (const RpcLayer__WriteRequest   *message,
                      ProtobufCBuffer     *buffer);
RpcLayer__WriteRequest *
       rpc_layer__write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpc_layer__write_request__free_unpacked
                     (RpcLayer__WriteRequest *message,
                      ProtobufCAllocator *allocator);
/* RpcLayer__WriteResponse methods */
void   rpc_layer__write_response__init
                     (RpcLayer__WriteResponse         *message);
size_t rpc_layer__write_response__get_packed_size
                     (const RpcLayer__WriteResponse   *message);
size_t rpc_layer__write_response__pack
                     (const RpcLayer__WriteResponse   *message,
                      uint8_t             *out);
size_t rpc_layer__write_response__pack_to_buffer
                     (const RpcLayer__WriteResponse   *message,
                      ProtobufCBuffer     *buffer);
RpcLayer__WriteResponse *
       rpc_layer__write_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rpc_layer__write_response__free_unpacked
                     (RpcLayer__WriteResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RpcLayer__ReadDirRequest_Closure)
                 (const RpcLayer__ReadDirRequest *message,
                  void *closure_data);
typedef void (*RpcLayer__ReadDirResponse_Closure)
                 (const RpcLayer__ReadDirResponse *message,
                  void *closure_data);
typedef void (*RpcLayer__GetAttrRequest_Closure)
                 (const RpcLayer__GetAttrRequest *message,
                  void *closure_data);
typedef void (*RpcLayer__GetAttrResponse_Closure)
                 (const RpcLayer__GetAttrResponse *message,
                  void *closure_data);
typedef void (*RpcLayer__ReadRequest_Closure)
                 (const RpcLayer__ReadRequest *message,
                  void *closure_data);
typedef void (*RpcLayer__ReadResponse_Closure)
                 (const RpcLayer__ReadResponse *message,
                  void *closure_data);
typedef void (*RpcLayer__WriteRequest_Closure)
                 (const RpcLayer__WriteRequest *message,
                  void *closure_data);
typedef void (*RpcLayer__WriteResponse_Closure)
                 (const RpcLayer__WriteResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct _RpcLayer__RemoteExt2_Service RpcLayer__RemoteExt2_Service;
struct _RpcLayer__RemoteExt2_Service
{
  ProtobufCService base;
  void (*read_dir)(RpcLayer__RemoteExt2_Service *service,
                   const RpcLayer__ReadDirRequest *input,
                   RpcLayer__ReadDirResponse_Closure closure,
                   void *closure_data);
  void (*get_attr)(RpcLayer__RemoteExt2_Service *service,
                   const RpcLayer__GetAttrRequest *input,
                   RpcLayer__GetAttrResponse_Closure closure,
                   void *closure_data);
  void (*read)(RpcLayer__RemoteExt2_Service *service,
               const RpcLayer__ReadRequest *input,
               RpcLayer__ReadResponse_Closure closure,
               void *closure_data);
  void (*write)(RpcLayer__RemoteExt2_Service *service,
                const RpcLayer__WriteRequest *input,
                RpcLayer__WriteResponse_Closure closure,
                void *closure_data);
};
typedef void (*RpcLayer__RemoteExt2_ServiceDestroy)(RpcLayer__RemoteExt2_Service *);
void rpc_layer__remote_ext2__init (RpcLayer__RemoteExt2_Service *service,
                                   RpcLayer__RemoteExt2_ServiceDestroy destroy);
#define RPC_LAYER__REMOTE_EXT2__BASE_INIT \
    { &rpc_layer__remote_ext2__descriptor, protobuf_c_service_invoke_internal, NULL }
#define RPC_LAYER__REMOTE_EXT2__INIT(function_prefix__) \
    { RPC_LAYER__REMOTE_EXT2__BASE_INIT,\
      function_prefix__ ## read_dir,\
      function_prefix__ ## get_attr,\
      function_prefix__ ## read,\
      function_prefix__ ## write  }
void rpc_layer__remote_ext2__read_dir(ProtobufCService *service,
                                      const RpcLayer__ReadDirRequest *input,
                                      RpcLayer__ReadDirResponse_Closure closure,
                                      void *closure_data);
void rpc_layer__remote_ext2__get_attr(ProtobufCService *service,
                                      const RpcLayer__GetAttrRequest *input,
                                      RpcLayer__GetAttrResponse_Closure closure,
                                      void *closure_data);
void rpc_layer__remote_ext2__read(ProtobufCService *service,
                                  const RpcLayer__ReadRequest *input,
                                  RpcLayer__ReadResponse_Closure closure,
                                  void *closure_data);
void rpc_layer__remote_ext2__write(ProtobufCService *service,
                                   const RpcLayer__WriteRequest *input,
                                   RpcLayer__WriteResponse_Closure closure,
                                   void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rpc_layer__read_dir_request__descriptor;
extern const ProtobufCMessageDescriptor rpc_layer__read_dir_response__descriptor;
extern const ProtobufCMessageDescriptor rpc_layer__get_attr_request__descriptor;
extern const ProtobufCMessageDescriptor rpc_layer__get_attr_response__descriptor;
extern const ProtobufCMessageDescriptor rpc_layer__read_request__descriptor;
extern const ProtobufCMessageDescriptor rpc_layer__read_response__descriptor;
extern const ProtobufCMessageDescriptor rpc_layer__write_request__descriptor;
extern const ProtobufCMessageDescriptor rpc_layer__write_response__descriptor;
extern const ProtobufCServiceDescriptor rpc_layer__remote_ext2__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_rpc_5flayer_2eproto__INCLUDED */
